@extends('layouts.app')
@section('title', 'Overview') @section('page-title', 'Good to see you, '.explode(' ', auth()->user()->name)[0])
@section('content')
<section class="welcome-banner"><div><p class="eyebrow">Your author studio</p><h2>What will you help readers discover today?</h2><p>Pick up a draft or open a fresh page for your next book.</p></div><a href="{{ route('projects.create') }}" class="button button-light">＋ Start a project</a></section>
<div class="section-heading compact"><div><p class="eyebrow">Continue creating</p><h2>Recent projects</h2></div><a href="{{ route('projects.index') }}" class="text-link">View all →</a></div>
<div class="project-grid">@forelse($projects as $project)<article class="project-card"><div class="project-cover"><span>{{ $project->asin ?: 'DRAFT' }}</span><strong>{{ $project->name }}</strong><small>{{ $project->genre ?: 'A+ CONTENT' }}</small></div><div class="project-card-body"><div class="card-meta"><span>{{ $project->modules_count }} modules</span><span>{{ $project->updated_at->diffForHumans() }}</span></div><h3>{{ $project->name }}</h3><p>{{ data_get($project->product_snapshot, 'title', 'Book details not linked yet') }}</p><a href="{{ route('projects.builder', $project) }}" class="button button-secondary button-wide">Open builder</a></div></article>@empty<div class="empty-card"><span>✦</span><h3>Your first page is waiting</h3><p>Start blank or shape a polished template around your book.</p><a href="{{ route('projects.create') }}" class="button button-primary">Create a project</a></div>@endforelse</div>
<div class="section-heading compact"><div><p class="eyebrow">Curated starting points</p><h2>Featured templates</h2></div><a href="{{ route('templates.index') }}" class="text-link">Browse gallery →</a></div>
<div class="mini-template-grid">@foreach($templates as $template)<a href="{{ route('templates.show', $template) }}" class="mini-template"><span>{{ $template->category }}</span><h3>{{ $template->name }}</h3><p>{{ $template->modules_count }} modules · {{ $template->summary }}</p></a>@endforeach</div>
@endsection
