@extends('layouts.public')
@section('title', 'Beautiful A+ content for books')
@section('content')
<section class="hero">
    <div class="hero-copy"><span class="pill">Built for independent authors</span><h1>Make your book page feel like <em>another chapter.</em></h1><p>Plan, write, illustrate, and preview Amazon KDP A+ Content in a focused studio—then carry every polished module into your book page.</p><div class="hero-actions"><a href="{{ route('register') }}" class="button button-primary button-large">Build your first page</a><a href="{{ route('templates.index') }}" class="button button-ghost button-large">Explore templates →</a></div><div class="hero-proof"><span>17 KDP-style modules</span><span>ASIN book lookup</span><span>AI-assisted copy & imagery</span></div></div>
    <div class="hero-visual hero-photo"><img src="{{ asset('images/landing/hero-publishing-studio.png') }}" alt="Author workspace with three book mockups and an A+ content campaign displayed on a laptop" fetchpriority="high"></div>
</section>
<section class="press-strip"><span>AUTHOR-FIRST WORKFLOW</span><span>•</span><span>PIXEL-GUIDED IMAGES</span><span>•</span><span>LIVE PREVIEW</span><span>•</span><span>AUTOSAVE</span></section>
<section class="section intro-section" id="how-it-works"><div><p class="eyebrow">A calmer way to build</p><h2>From ASIN to finished story in three thoughtful steps.</h2></div><p>Amazon’s modules are powerful, but composing inside the publishing flow can feel cramped. Work here first—with room to experiment—then transfer a clean, validated package.</p></section>
<section class="steps-grid"><article><span>01</span><div class="step-icon">⌕</div><h3>Find your book</h3><p>Look up an ASIN and bring the title, cover, and product context into your workspace.</p></article><article><span>02</span><div class="step-icon">▦</div><h3>Shape the page</h3><p>Start blank or choose an editorial template, then arrange purpose-built content modules.</p></article><article><span>03</span><div class="step-icon">↗</div><h3>Transfer with confidence</h3><p>Preview, validate, and export organized copy and correctly labeled imagery for KDP.</p></article></section>
<section class="section showcase" id="examples"><div class="showcase-copy"><p class="eyebrow">Designed around books</p><h2>Not another generic product-page builder.</h2><p>Your imagery, tone, audience, and storyworld stay at the center. The result feels editorial and distinctive—whether you write epic fantasy, practical nonfiction, or picture books.</p><ul><li>Genre-aware starter templates</li><li>Book-focused AI writing context</li><li>Exact image dimensions at every slot</li><li>Alt text built into the workflow</li></ul><a href="{{ route('templates.index') }}" class="text-link">Browse the full gallery →</a></div><div class="showcase-photo"><img src="{{ asset('images/landing/designed-around-books.png') }}" alt="The Last Lighthouse hardcover beside a coordinated panoramic book marketing campaign and feature cards" loading="lazy"></div></section>
<section class="section templates-preview"><div class="section-heading"><div><p class="eyebrow">Begin with a point of view</p><h2>Templates for the way authors sell stories.</h2></div><a href="{{ route('templates.index') }}" class="button button-secondary">View all 12 templates</a></div><div class="template-grid">@forelse($templates as $template)<article class="template-card"><a href="{{ route('templates.show', $template) }}" class="template-preview-image"><img src="{{ $template->preview_image }}" alt="{{ $template->name }} preview" loading="lazy"></a><div><span class="pill pill-small">{{ $template->category }}</span><h3>{{ $template->name }}</h3><p>{{ $template->summary }}</p><a href="{{ route('templates.show', $template) }}">Preview template →</a></div></article>@empty<p>Template previews are added when the database is seeded.</p>@endforelse</div></section>
<section class="final-cta"><p class="eyebrow">Your next page starts here</p><h2>Give readers more reasons to choose your book.</h2><p>Build at your own pace. Start from a template or a beautifully blank page.</p><a href="{{ route('register') }}" class="button button-light button-large">Create your free studio</a></section>
@endsection
