@php
    $isTemplateEditor = in_array(($editorMode ?? 'project'), ['template', 'template-create'], true);
    $isNewTemplate = ($editorMode ?? 'project') === 'template-create';
    $editorEntity = $isTemplateEditor ? $template : $project;
    $editorAssets = $isTemplateEditor ? $assets : $project->assets;
@endphp
@extends('layouts.app')
@section('title', $editorEntity->name ?: 'New template') @section('page-title', $editorEntity->name ?: 'New template')
@section('content')
<div id="builder" class="builder {{ $isTemplateEditor ? 'template-builder' : '' }}" data-project="{{ $isTemplateEditor ? ($template->slug ?: 'new-template') : $project->uuid }}">
    <header class="builder-toolbar"><div class="builder-tabs" role="tablist"><button class="active" data-builder-tab="editor" role="tab">Editor</button><button data-builder-tab="preview" role="tab">Preview</button></div><div class="save-state" id="save-state"><span></span>{{ $isNewTemplate ? 'Save gallery details to begin' : 'All changes saved' }}</div><div class="builder-actions"><button class="button button-secondary" id="validate-project" type="button">Check content</button>@if($isTemplateEditor && !$isNewTemplate)<a class="button button-primary" href="{{ route('templates.show', $template) }}">View gallery page</a>@elseif(!$isTemplateEditor)<a class="button button-primary" id="open-transfer-guide" href="{{ route('projects.transfer', $project) }}">Copy to KDP</a>@endif</div></header>
    <div class="book-context">@if(!$isTemplateEditor && data_get($project->product_snapshot, 'image_url'))<img src="{{ data_get($project->product_snapshot, 'image_url') }}" alt="">@endif<div><span>{{ $isTemplateEditor ? ucfirst($template->status ?: 'draft').' template' : ($project->asin ?: 'No ASIN linked') }}</span><strong>{{ $isTemplateEditor ? ($template->name ?: 'New gallery template') : data_get($project->product_snapshot, 'title', $project->name) }}</strong></div>@if(!$isTemplateEditor)<button class="text-button" type="button" id="edit-context">Project context</button>@endif</div>
    <div class="builder-workspace"><aside class="builder-outline">@if($isTemplateEditor)<form id="gallery-details-form" class="gallery-details-sidebar"><p class="eyebrow">Gallery details</p><label>Name<input name="name" value="{{ $template->name }}" required maxlength="120"></label><label>Summary<input name="summary" value="{{ $template->summary }}" maxlength="240"></label><label>Description<textarea name="description" rows="3" maxlength="3000">{{ $template->description }}</textarea></label><label>Category<input name="category" value="{{ $template->category }}" maxlength="80"></label><label>Tags<input name="tags" value="{{ implode(', ', $template->tags ?? []) }}"></label><label>Status<select name="status"><option value="draft" @selected($template->status === 'draft')>Draft</option><option value="published" @selected($template->status === 'published')>Published</option><option value="archived" @selected($template->status === 'archived')>Archived</option></select></label><label class="check-row"><input type="checkbox" name="is_featured" value="1" @checked($template->is_featured)> Featured</label><button type="submit" class="button button-secondary button-wide">Save gallery details</button></form>@endif<div class="outline-head"><strong>Page outline</strong></div><ol id="module-outline"></ol><button type="button" class="button button-secondary button-wide" data-open-module-dialog>＋ Add module</button><p class="module-limit-message" id="module-limit-message" hidden>Amazon limits A+ Content to 5 modules.</p><button type="button" class="asset-summary" id="open-asset-manager"><span>Assets</span><strong>{{ $editorAssets->count() }} images</strong></button></aside><section class="builder-canvas" data-panel="editor"><section id="image-filter-editor" class="filter-editor"></section><div id="module-list"></div><div class="builder-empty" id="builder-empty"><div class="step-icon">＋</div><h2>Begin your page</h2><p>Choose a KDP-style module and make it yours.</p><button type="button" class="button button-primary" data-open-module-dialog>Add your first module</button></div></section><section class="preview-panel" data-panel="preview" hidden><div class="preview-tools"><span>Page preview</span><div><button class="active" type="button" data-preview-width="desktop">Desktop</button><button type="button" data-preview-width="mobile">Mobile</button></div></div><div class="preview-frame" id="preview-frame"><div id="preview-content"></div></div></section></div>
</div>

<dialog id="module-dialog" class="studio-dialog"><form method="dialog" class="dialog-shell"><header><div><p class="eyebrow">Module library</p><h2>Add a module</h2></div><button value="cancel" class="icon-button" aria-label="Close">×</button></header><div class="dialog-search"><input type="search" id="module-search" placeholder="Search layouts, text, images, comparisons…">@if(!$isTemplateEditor)<label class="module-sample-option"><input type="checkbox" id="populate-module-samples" checked><span><strong>Populate with sample images and text</strong><small>Uncheck to add the selected module empty.</small></span></label>@else<input type="checkbox" id="populate-module-samples" hidden>@endif</div><div class="module-gallery" id="module-gallery"></div></form></dialog>
<dialog id="asset-dialog" class="studio-dialog asset-dialog"><div class="dialog-shell"><header><div><p class="eyebrow">Asset manager</p><h2>Choose an image</h2></div><button type="button" class="icon-button" data-close-dialog="asset-dialog" aria-label="Close">×</button></header><div class="asset-library-tools"><label class="button button-secondary" for="asset-file">Upload image<input type="file" id="asset-file" accept="image/jpeg,image/png,image/webp"></label><button type="button" class="button button-secondary" id="asset-stock-search-open">Search stock images</button><button type="button" class="button button-secondary" id="asset-ai-open" @if($isTemplateEditor) hidden @endif>✦ Generate with AI</button><input type="search" id="asset-search" placeholder="Search by file name or alt text" aria-label="Search images"><span id="asset-requirement" class="field-hint"></span></div><div class="asset-library" id="asset-library"></div><footer><button type="button" class="button button-ghost" data-close-dialog="asset-dialog">Cancel</button></footer></div></dialog>

<dialog id="asset-stock-search-dialog" class="studio-dialog stock-search-dialog"><div class="dialog-shell"><header><div><p class="eyebrow">Stock image search</p><h2>Find an image</h2></div><button type="button" class="icon-button" data-close-dialog="asset-stock-search-dialog" aria-label="Close">×</button></header><form id="asset-stock-search-form" class="stock-search-tools"><label>Search<input type="search" id="asset-stock-search-query" required maxlength="150" placeholder="e.g. red apple on a table"></label><label>Provider<select id="asset-stock-search-provider"><option value="pexels" selected>Pexels</option><option value="unsplash">Unsplash</option><option value="pixabay">Pixabay</option></select></label><label>Page size<select id="asset-stock-search-page-size">@foreach([10, 20, 30, 40, 50, 60, 70, 80, 90, 100] as $size)<option value="{{ $size }}" @selected($size === 10)>{{ $size }}</option>@endforeach</select></label><button type="submit" class="button button-primary" id="asset-stock-search-submit">Search</button></form><div class="stock-search-summary" id="asset-stock-search-summary">Enter a search to find stock images.</div><div class="stock-search-results" id="asset-stock-search-results"><div class="asset-library-empty"><strong>No search yet</strong><span>Results from Pexels, Unsplash, and Pixabay will appear here.</span></div></div><footer><button type="button" class="button button-ghost" id="asset-stock-search-back">Back to library</button><div class="stock-search-pagination"><button type="button" class="button button-secondary" id="asset-stock-search-previous" disabled>Previous</button><span id="asset-stock-search-page">Page 1</span><button type="button" class="button button-secondary" id="asset-stock-search-next" disabled>Next</button></div></footer></div></dialog>

<dialog id="asset-details-dialog" class="studio-dialog asset-details-dialog"><form class="dialog-shell" id="asset-details-form"><header><div><p class="eyebrow">Asset manager</p><h2>Image details</h2></div><button type="button" class="icon-button" data-close-dialog="asset-details-dialog" aria-label="Close">×</button></header><div class="asset-details-body"><div class="asset-detail-preview" id="asset-detail-preview"></div><div class="asset-detail-fields"><strong id="asset-detail-name"></strong><span id="asset-detail-dimensions" class="field-hint"></span><label>Alt text<input id="asset-alt" name="alt_text" required maxlength="250" placeholder="Describe the image for readers who cannot see it"></label><p class="field-hint">Alt text helps readers who cannot see the image understand its purpose.</p></div></div><footer><button type="button" class="button button-ghost" id="asset-details-back">Back</button><button type="submit" class="button button-secondary" id="asset-details-save">Save details</button><button type="button" class="button button-primary" id="asset-details-use">Use image</button></footer></form></dialog>

<dialog id="crop-dialog" class="studio-dialog crop-dialog"><div class="dialog-shell"><header><div><p class="eyebrow">Fit image</p><h2>Crop to <span id="crop-target-label"></span></h2></div><button type="button" class="icon-button" data-close-dialog="crop-dialog" aria-label="Close">×</button></header><div class="crop-body"><div class="crop-stage" id="crop-stage"><canvas id="crop-canvas"></canvas><span>Drag to reposition</span></div><div class="crop-controls"><label>Zoom<input type="range" id="crop-zoom" min="1" max="4" step="0.01" value="1"></label><div><button type="button" class="button button-secondary" id="crop-rotate-left" aria-label="Rotate left">↶ Rotate left</button><button type="button" class="button button-secondary" id="crop-rotate-right" aria-label="Rotate right">↷ Rotate right</button></div><p class="field-hint">The image must completely fill the target. Zoom and positioning are limited to prevent empty space.</p></div></div><footer><button type="button" class="button button-ghost" id="crop-back">Back</button><button type="button" class="button button-primary" id="crop-apply">Crop and use</button></footer></div></dialog>

<dialog id="asset-ai-dialog" class="studio-dialog ai-dialog"><form class="dialog-shell" id="asset-ai-form"><header><div><p class="eyebrow">AI image studio</p><h2>Generate an image</h2></div><button type="button" class="icon-button" data-close-dialog="asset-ai-dialog" aria-label="Close">×</button></header><div class="asset-modal-body"><label>Image direction<textarea id="asset-ai-prompt" rows="4" required placeholder="A cinematic starship crossing a violet nebula, no typography…"></textarea></label><label>Alt text<input id="asset-ai-alt" required maxlength="250" placeholder="Describe the generated image"></label><p class="field-hint">The image will be generated at the target size and added directly.</p></div><footer><button type="button" class="button button-ghost" id="asset-ai-back">Back</button><button type="submit" class="button button-primary" id="asset-ai-generate">Generate and use</button></footer></form></dialog>
<dialog id="ai-dialog" class="studio-dialog ai-dialog"><form class="dialog-shell" id="ai-form"><header><div><p class="eyebrow">AI writing partner</p><h2>Draft module copy</h2></div><button type="button" class="icon-button" data-close-dialog="ai-dialog" aria-label="Close">×</button></header><div class="asset-modal-body"><p>Book details and your project context will guide the draft. Review every word before applying it.</p><label>What should this module communicate?<textarea id="ai-prompt" rows="5" required placeholder="Focus on the found-family theme and the scale of the adventure…"></textarea></label><div id="ai-result"></div></div><footer><button type="button" class="button button-ghost" data-close-dialog="ai-dialog">Cancel</button><button type="submit" class="button button-primary" id="ai-generate">Generate draft</button></footer></form></dialog>

<script id="builder-data" type="application/json">{!! json_encode([
    'mode' => $isTemplateEditor ? ($isNewTemplate ? 'template-create' : 'template') : 'project',
    'project' => $isTemplateEditor ? ['uuid' => $template->slug, 'name' => $template->name] : $project->only(['uuid','name','asin','author_name','genre','audience','tone','brand_notes','product_snapshot']),
    'modules' => $isTemplateEditor ? ($template->exists ? $template->modules->map(fn($module) => ['uuid' => $module->id, 'module_type' => $module->module_type, 'position' => $module->position, 'content' => $module->content, 'settings' => $module->settings]) : []) : $project->modules->map(fn($module) => $module->only(['uuid','module_type','position','content','settings','version'])),
    'assets' => $editorAssets,
    'registry' => $registry,
    'image_filters' => $editorEntity->image_filters ?? [],
    'moduleLimit' => \App\Models\Project::MAX_MODULES,
    'routes' => [
        'moduleStore' => $isTemplateEditor ? ($isNewTemplate ? null : route('admin.templates.modules.store', $template)) : route('projects.modules.store', $project),
        'moduleBase' => $isTemplateEditor ? ($isNewTemplate ? null : url('/admin/templates/'.$template->slug.'/modules')) : url('/projects/'.$project->uuid.'/modules'),
        'reorder' => $isTemplateEditor ? ($isNewTemplate ? null : route('admin.templates.modules.reorder', $template)) : route('projects.modules.reorder', $project),
        'assets' => $isTemplateEditor ? route('admin.template-assets.store') : route('projects.assets.store', $project),
        'assetSearch' => route('assets.search'),
        'assetImport' => $isTemplateEditor ? route('admin.template-assets.import') : route('projects.assets.import', $project),
        'assetBase' => url('/assets'),
        'asinImport' => $isTemplateEditor ? null : route('projects.asin.import', $project),
        'aiText' => $isTemplateEditor ? null : route('projects.ai.text', $project),
        'aiImage' => $isTemplateEditor ? null : route('projects.ai.image', $project),
        'entitySave' => $isTemplateEditor ? ($isNewTemplate ? route('admin.templates.store') : route('admin.templates.update', $template)) : route('projects.update', $project),
    ],
], JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) !!}</script>
@endsection
