@extends('layouts.app')
@section('title', $project->name) @section('page-title', $project->name)
@section('content')
<div id="builder" class="builder" data-project="{{ $project->uuid }}">
    <header class="builder-toolbar"><div class="builder-tabs" role="tablist"><button class="active" data-builder-tab="editor" role="tab">Editor</button><button data-builder-tab="preview" role="tab">Preview</button></div><div class="save-state" id="save-state"><span></span>All changes saved</div><div class="builder-actions"><button class="button button-secondary" id="validate-project" type="button">Check content</button><form method="POST" action="{{ route('projects.export', $project) }}">@csrf<button class="button button-primary" type="submit">Export for KDP</button></form></div></header>
    <div class="book-context">@if(data_get($project->product_snapshot, 'image_url'))<img src="{{ data_get($project->product_snapshot, 'image_url') }}" alt="">@endif<div><span>{{ $project->asin ?: 'No ASIN linked' }}</span><strong>{{ data_get($project->product_snapshot, 'title', $project->name) }}</strong></div><button class="text-button" type="button" id="edit-context">Project context</button></div>
    <div class="builder-workspace"><aside class="builder-outline"><div class="outline-head"><strong>Page outline</strong><button type="button" class="icon-button" data-open-module-dialog aria-label="Add module">＋</button></div><ol id="module-outline"></ol><button type="button" class="button button-secondary button-wide" data-open-module-dialog>＋ Add module</button><p class="module-limit-message" id="module-limit-message" hidden>Amazon limits A+ Content to 5 modules.</p><button type="button" class="asset-summary" id="open-asset-manager"><span>Assets</span><strong>{{ $project->assets->count() }} images</strong></button></aside><section class="builder-canvas" data-panel="editor"><div id="module-list"></div><div class="builder-empty" id="builder-empty"><div class="step-icon">＋</div><h2>Begin your page</h2><p>Choose a KDP-style module and make it yours.</p><button type="button" class="button button-primary" data-open-module-dialog>Add your first module</button></div></section><section class="preview-panel" data-panel="preview" hidden><div class="preview-tools"><span>Page preview</span><div><button class="active" type="button" data-preview-width="desktop">Desktop</button><button type="button" data-preview-width="mobile">Mobile</button></div></div><div class="preview-frame" id="preview-frame"><div id="preview-content"></div></div></section></div>
</div>

<dialog id="module-dialog" class="studio-dialog"><form method="dialog" class="dialog-shell"><header><div><p class="eyebrow">Module library</p><h2>Add a module</h2></div><button value="cancel" class="icon-button" aria-label="Close">×</button></header><div class="dialog-search"><input type="search" id="module-search" placeholder="Search layouts, text, images, comparisons…"><label class="module-sample-option"><input type="checkbox" id="populate-module-samples" checked><span><strong>Populate with sample images and text</strong><small>Uncheck to add the selected module empty.</small></span></label></div><div class="module-gallery" id="module-gallery"></div></form></dialog>
<dialog id="asset-dialog" class="studio-dialog asset-dialog"><div class="dialog-shell"><header><div><p class="eyebrow">Asset manager</p><h2>Choose an image</h2></div><button type="button" class="icon-button" data-close-dialog="asset-dialog" aria-label="Close">×</button></header><div class="asset-library-tools"><label class="button button-secondary" for="asset-file">Upload image<input type="file" id="asset-file" accept="image/jpeg,image/png,image/webp"></label><button type="button" class="button button-secondary" id="asset-ai-open">✦ Generate with AI</button><input type="search" id="asset-search" placeholder="Search by file name or alt text" aria-label="Search images"><span id="asset-requirement" class="field-hint"></span></div><div class="asset-library" id="asset-library"></div><footer><button type="button" class="button button-ghost" data-close-dialog="asset-dialog">Cancel</button></footer></div></dialog>

<dialog id="asset-details-dialog" class="studio-dialog asset-details-dialog"><form class="dialog-shell" id="asset-details-form"><header><div><p class="eyebrow">Asset manager</p><h2>Image details</h2></div><button type="button" class="icon-button" data-close-dialog="asset-details-dialog" aria-label="Close">×</button></header><div class="asset-details-body"><div class="asset-detail-preview" id="asset-detail-preview"></div><div class="asset-detail-fields"><strong id="asset-detail-name"></strong><span id="asset-detail-dimensions" class="field-hint"></span><label>Alt text<input id="asset-alt" name="alt_text" required maxlength="250" placeholder="Describe the image for readers who cannot see it"></label><p class="field-hint">Alt text helps readers who cannot see the image understand its purpose.</p></div></div><footer><button type="button" class="button button-ghost" id="asset-details-back">Back</button><button type="submit" class="button button-secondary" id="asset-details-save">Save details</button><button type="button" class="button button-primary" id="asset-details-use">Use image</button></footer></form></dialog>

<dialog id="crop-dialog" class="studio-dialog crop-dialog"><div class="dialog-shell"><header><div><p class="eyebrow">Fit image</p><h2>Crop to <span id="crop-target-label"></span></h2></div><button type="button" class="icon-button" data-close-dialog="crop-dialog" aria-label="Close">×</button></header><div class="crop-body"><div class="crop-stage" id="crop-stage"><canvas id="crop-canvas"></canvas><span>Drag to reposition</span></div><div class="crop-controls"><label>Zoom<input type="range" id="crop-zoom" min="1" max="4" step="0.01" value="1"></label><div><button type="button" class="button button-secondary" id="crop-rotate-left" aria-label="Rotate left">↶ Rotate left</button><button type="button" class="button button-secondary" id="crop-rotate-right" aria-label="Rotate right">↷ Rotate right</button></div><p class="field-hint">The image must completely fill the target. Zoom and positioning are limited to prevent empty space.</p></div></div><footer><button type="button" class="button button-ghost" id="crop-back">Back</button><button type="button" class="button button-primary" id="crop-apply">Crop and use</button></footer></div></dialog>

<dialog id="asset-ai-dialog" class="studio-dialog ai-dialog"><form class="dialog-shell" id="asset-ai-form"><header><div><p class="eyebrow">AI image studio</p><h2>Generate an image</h2></div><button type="button" class="icon-button" data-close-dialog="asset-ai-dialog" aria-label="Close">×</button></header><div class="asset-modal-body"><label>Image direction<textarea id="asset-ai-prompt" rows="4" required placeholder="A cinematic starship crossing a violet nebula, no typography…"></textarea></label><label>Alt text<input id="asset-ai-alt" required maxlength="250" placeholder="Describe the generated image"></label><p class="field-hint">The image will be generated at the target size and added directly.</p></div><footer><button type="button" class="button button-ghost" id="asset-ai-back">Back</button><button type="submit" class="button button-primary" id="asset-ai-generate">Generate and use</button></footer></form></dialog>
<dialog id="ai-dialog" class="studio-dialog ai-dialog"><form class="dialog-shell" id="ai-form"><header><div><p class="eyebrow">AI writing partner</p><h2>Draft module copy</h2></div><button type="button" class="icon-button" data-close-dialog="ai-dialog" aria-label="Close">×</button></header><div class="asset-modal-body"><p>Book details and your project context will guide the draft. Review every word before applying it.</p><label>What should this module communicate?<textarea id="ai-prompt" rows="5" required placeholder="Focus on the found-family theme and the scale of the adventure…"></textarea></label><div id="ai-result"></div></div><footer><button type="button" class="button button-ghost" data-close-dialog="ai-dialog">Cancel</button><button type="submit" class="button button-primary" id="ai-generate">Generate draft</button></footer></form></dialog>

<script id="builder-data" type="application/json">{!! json_encode([
    'project' => $project->only(['uuid','name','asin','author_name','genre','audience','tone','brand_notes','product_snapshot']),
    'modules' => $project->modules->map(fn($module) => $module->only(['uuid','module_type','position','content','settings','version'])),
    'assets' => $project->assets,
    'registry' => $registry,
    'moduleLimit' => \App\Models\Project::MAX_MODULES,
    'routes' => [
        'moduleStore' => route('projects.modules.store', $project),
        'moduleBase' => url('/projects/'.$project->uuid.'/modules'),
        'reorder' => route('projects.modules.reorder', $project),
        'assets' => route('projects.assets.store', $project),
        'assetBase' => url('/assets'),
        'asinImport' => route('projects.asin.import', $project),
        'aiText' => route('projects.ai.text', $project),
        'aiImage' => route('projects.ai.image', $project),
    ],
], JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) !!}</script>
@endsection
