@extends('layouts.app')
@section('title', 'AI call logs') @section('page-title', 'AI call logs')
@section('content')
<div class="page-lead"><div><p class="eyebrow">Administration</p><h2>Every model call, in one audit trail.</h2><p>{{ number_format($totals->calls) }} completed calls · ${{ number_format((float) $totals->cost, 6) }} recorded cost</p></div><a href="{{ route('admin.ai.settings') }}" class="button button-secondary">AI settings</a></div>
<form method="GET" class="gallery-filters ai-log-filters"><input type="search" name="search" value="{{ request('search') }}" placeholder="Search model, location, or user"><select name="kind"><option value="">All types</option><option value="text" @selected(request('kind') === 'text')>Text</option><option value="image" @selected(request('kind') === 'image')>Image</option></select><select name="status"><option value="">All statuses</option><option value="succeeded" @selected(request('status') === 'succeeded')>Succeeded</option><option value="failed" @selected(request('status') === 'failed')>Failed</option></select><button class="button button-secondary">Filter</button></form>
<div class="table-card"><table><thead><tr><th>When</th><th>User</th><th>Used in</th><th>Model</th><th>Tokens</th><th>Cost</th><th>Status</th></tr></thead><tbody>
@forelse($logs as $log)<tr><td>{{ $log->created_at->format('M j, Y H:i') }}</td><td><strong>{{ $log->user?->name ?? 'Deleted user' }}</strong><small>{{ $log->user?->email }}</small></td><td><strong>{{ str($log->location)->replace('.', ' ')->headline() }}</strong><small>{{ $log->project?->name }}@if(data_get($log->metadata, 'module_type')) · {{ data_get($log->metadata, 'module_type') }}@endif</small></td><td><strong>{{ $log->model }}</strong><small>{{ ucfirst($log->kind) }} · {{ $log->duration_ms }} ms</small></td><td>{{ number_format($log->total_tokens ?? 0) }}<small>{{ number_format($log->input_tokens ?? 0) }} in · {{ number_format($log->output_tokens ?? 0) }} out</small></td><td>{{ $log->cost_usd === null ? '—' : '$'.number_format((float) $log->cost_usd, 8) }}</td><td><span class="status status-{{ $log->status === 'succeeded' ? 'published' : 'archived' }}">{{ ucfirst($log->status) }}</span>@if($log->error_message)<small title="{{ $log->error_message }}">{{ str($log->error_message)->limit(70) }}</small>@endif</td></tr>
@empty<tr><td colspan="7">No AI calls match these filters.</td></tr>@endforelse
</tbody></table></div>{{ $logs->links() }}
@endsection
